name: fill-diff
on: [pull_request]
jobs:
  oldfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed-files
        id: changes
        # Set outputs using the command.
        run: sudo ./.github/workflows/scripts/gitdiff.sh
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test dates
        env:
          GITHUB_OLD_DATE: ${{ env.GITHUB_OLD_DATE }}
          GITHUB_NEW_DATE: ${{ env.GITHUB_NEW_DATE }}
        run: python ./.github/workflows/scripts/compare_review_dates.py
