name: fill-diff
on: [pull_request]
jobs:
  oldfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed-files
        id: changes
        # Set outputs using the command.
        run: |
          git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -U0
