name: fill-diff
on: [pull_request]
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      olddate: ${{ steps.changes.outputs.olddate}}
      newdate: ${{ steps.changes.outputs.newdate }}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed-files
        id: changes
        # Set outputs using the command.
        run: |
          echo "GITHUB_OLD_DATE=$(git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -U0 | grep 'review_date:' | cut -d\  -f2 | tail -n +2| head -n 1)" >> $GITHUB_ENV
      - name: test-changed-files
        run: |
          echo "GITHUB_NEW_DATE=$(git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -U0 | grep 'review_date:' | cut -d\  -f2 | tail -n 1)" >> $GITHUB_ENV
          echo $GITHUB_OLD_DATE
      - name: test dates
        run: |
          python3 -c \
          'from datetime import datetime as dt;'\
          'import os;'\
          'print(os.getenv['GITHUB_NEW_DATE']);'\
          '#date_diff = dt.strptime(os.environ['GITHUB_NEW_DATE'], "%Y-%m-%d") - dt.strptime(os.environ['GITHUB_OLD_DATE'], "%Y-%m-%d")'
          '#if data_diff.days > 92: raise ValueError("date diff to high");'\
