name: fill-diff
on: [pull_request]
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      newdate: ${{steps.newchanges.outputs.newdate }}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: changed-files2
        id: newchanges
        # Set outputs using the command.
        run: |
          echo "::set-output name=newdate::$(git diff --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -U0 | grep 'review_date:' | cut -d\  -f2 | tail -n 1)"
      - name: Set up Pyton 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test dates
        env:
          GITHUB_NEW_DATE: ${{steps.newchanges.outputs.newdate}}
        run: python ./.github/workflows/scripts/compare_review_dates.py
